version: 0.1.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
build_script:
- cmd: >-
    dotnet publish -c Release -r win-x64 --self-contained false -f net5.0-windows -o bin/wowdatabaseeditor/

    7z a WoWDatabaseEditor.zip bin/wowdatabaseeditor/*
artifacts:
- path: WoWDatabaseEditor.zip
  name: WoWDatabaseEditor.zip
